# This workflow will run the tests on the CSGOML repo

name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.10'
      - name: Checkout CSGOML library
        uses: actions/checkout@v3
      - name: Installation
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install pytest-cov
          pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --ignore=E501 --max-complexity=20 --statistics
      - name: Test with pytest
        run: |
          coverage run -m pytest --durations=10
          coverage report -m
          
