# This workflow will run the tests on the CSGOML repo

name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3800 # Optional, default value is 3306. The port of host
          container port: 3307 # Optional, default value is 3306. The port of container
          mysql version: '8.0' # Optional, default value is "latest". The version of the MySQL
          mysql database: 'analyzertest' # Optional, default value is "test". The specified database which will be create
          mysql root password: 'testpassword' # Required if "mysql user" is empty, default is empty. The root superuser password
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Checkout CSGOML library
        uses: actions/checkout@v3
      - name: Installation
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install pytest-cov
          pip install flake8
          pip install mypy
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --ignore=W503,E265 --max-complexity=20 --max-line-length=240 --statistics
      - name: Typecheck with mypy
        run: |
          mypy --install-types --non-interactive --check-untyped-defs --ignore-missing-imports -p csgoml
      - name: Test with pytest
        run: |
          coverage run -m pytest --durations=10
          coverage report -m
          coverage html
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: htmlcov/

